ark:
  doc:
    enabled: true
    example-token:
  sdk:
    jwt:
      expire-secs: 60
      secret: secret
      issuer: Ark-Frameword
    http:
      enable-request-body-decryption: false
      enable-response-body-encryption: false
  system:
    initial-password: '000000'
    log:
      enabled: true
    default-subscriber-service: com.scfsoft.system.service.SubscriberServiceDbImpl
  web:
    auth:
      patterns: /system/**,/profile/**,/workflow/**,/logout
spring:
  cache:
    type: Simple
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        max-active: 30
        min-idle: 5
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 50
        filters: stat,wall
        use-global-data-source-stat: true
        wall:
          condition-and-alway-true-allow: true
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://192.168.1.191:30333/test?useUnicode=true&characterEncoding=utf8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: ${spring.jpa.database}
  params: count=countSql
logging:
  level:
    root: info
#    com.scfsoft: debugs
